version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "3306:3306"
    environment:
      - DB_HOST=host.docker.internal




