# Generated by Django 3.0.14 on 2023-05-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_chosungs',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
