# Generated by Django 3.0.14 on 2023-05-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvalidatedToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='주기적으로 삭제 필요 or redis exp 사용')),
            ],
        ),
    ]
