# Generated by Django 3.0.14 on 2023-05-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidatedtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
